parameters:
#    site_gsb_med_gsb_med.example.class: SiteGsbMed\GsbMedBundle\Example

services:
#    site_gsb_med_gsb_med.example:
#        class: %site_gsb_med_gsb_med.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
